# Required metadata
sonar.projectKey=regime-apk
sonar.projectName=regime-apk
sonar.projectVersion=1.0

# Path to the source code
# Since this file is in the 'backend' folder, use '.' for current directory
sonar.sources=.

# Language of the project
sonar.language=py
sonar.python.version=3

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Exclude specific files and directories from analysis
sonar.exclusions=**/migrations/**, **/tests.py, venv/**, staticfiles/**, media/**, manage.py, core/asgi.py, core/wsgi.py

# Path to tests for coverage analysis
sonar.tests=.
sonar.test.inclusions=**/tests.py, **/test_*.py

# Coverage reporting (if you use coverage.py)
# sonar.python.coverage.reportPaths=coverage.xml

# Quality Gate and Issue Tracking
sonar.host.url=http://host.docker.internal:9000

sonar.login=sqp_455706dcec3722e821e827312ba17ff2a9338d61
