# Generated by Django 5.2.8 on 2025-12-08 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatsession_options_chatsession_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.AddField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default='user', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='tokens_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_name',
            field=models.CharField(default='New Chat', max_length=200),
        ),
    ]
