# Generated by Django 5.2.8 on 2025-12-08 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0003_dailylog_progressphoto_delete_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.ImageField(blank=True, null=True, upload_to='progress/badges/')),
                ('criteria', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dailylog',
            name='chest_cm',
            field=models.FloatField(blank=True, help_text='Tour de poitrine', null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='hip_cm',
            field=models.FloatField(blank=True, help_text='Tour de hanches', null=True),
        ),
        migrations.AddField(
            model_name='dailylog',
            name='waist_cm',
            field=models.FloatField(blank=True, help_text='Tour de taille', null=True),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progress.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'badge')},
            },
        ),
    ]
