# Generated by Django 5.2.8 on 2025-12-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_currency_user_date_of_birth_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_level',
            field=models.CharField(choices=[('SED', "Sédentaire (Peu ou pas d'exercice)"), ('LIG', 'Léger (Exercice 1-3 jours/semaine)'), ('MOD', 'Modéré (Exercice 3-5 jours/semaine)'), ('ACT', 'Actif (Exercice 6-7 jours/semaine)'), ('VER', 'Très actif (Physique + Entraînement)')], default='SED', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='current_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_calorie_goal',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='target_weight_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10, null=True),
        ),
    ]
