# Generated by Django 5.2.8 on 2026-02-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_activity_level_user_current_weight_kg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', max_length=20),
        ),
    ]
