# Generated by Django 5.2.8 on 2026-02-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_healthprofile_usergoal_userpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergoal',
            name='effort_level',
            field=models.CharField(choices=[('Low', 'Low'), ('Moderate', 'Moderate'), ('High', 'High')], default='Moderate', max_length=20),
        ),
    ]
