# Generated by Django 5.2.8 on 2026-02-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_healthprofile_stress_level_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='cuisine_type',
            field=models.CharField(blank=True, choices=[('Mediterranean', 'Mediterranean'), ('Asian', 'Asian'), ('Western', 'Western'), ('Middle Eastern', 'Middle Eastern'), ('African', 'African'), ('Latin American', 'Latin American'), ('French', 'French'), ('Italian', 'Italian'), ('Japanese', 'Japanese'), ('Indian', 'Indian'), ('Other', 'Other')], max_length=100, null=True),
        ),
    ]
